." +AMDG
." Process with:
." groff -man -Tascii minlib.1
.TH minlib 1 "June 2016" dgoodmaniii minlib
.SH NAME
minlib \- a text-based library management program
.SH SYNOPSIS
.B minlib
[\fB\-r\fR \fIformatstring\fR]
[\fB\-f\fR \fIinputfile[,...]\fR]
.SH DESCRIPTION
.B minlib
A text-based library management program, designed to do one
thing---manage your library, physical and digital---and do
it well. Customizable formatting, usable with books, files,
movies, music or any other media.  Features include
filtering, searching, and more.
.SH OPTIONS
.TP
.BR \-V
Print version and licensing information, then exit
successfully.
.TP
.BR "\-f \fIfilename\fR"
Use \fIfilename\fR as the source of library records.  You
can supply a comma-separated list of source files in this
argument, and \fBminlib\fR will do the right thing and use
them all, by dumping them all into a temporary file and then
inputting that.
.TP
.BR "\-r \fIrecord-format\fR"
Use \fIrecord-format\fR as the format for each individual
record outputted by \fBminlib\fR.  By default, this is
\fB%29t | %20L | %10F | %4l | %4g\fR, which the astute
reader will see adds to precisely the default terminal width
of 80 characters.  The format is similar to that of C's
printf, in that we use a percent sign, followed by a number,
followed by a single character which specifies what to fill
in, but it is quite different from that of C's printf in
that it requires that each formatting character be
accompanied by a number of characters.  Given the extreme
variability of field lengths, and the extreme limitation of
most terminals, this restriction seems reasonable.
.RS
.HP
Interpreted sequences are:
.TP 
%t
The title; matched with field heading TITLE.
.TP
%L
The author's last name; matched with field heading AUTHLAST.
.TP
%M
The author's middle name; matched with field heading
AUTHMID.
.TP
%F
The author's first name; matched with field heading
AUTHFIRST.
.TP
%l
The language of the work; matched with field heading LANG.
.TP
%g
The genre, or type, of the work; matched with field headings
TYPE or GENRE.
.TP
%y
The year of the work; matched with field heading YEAR.
.TP
%m
Media of the work; e.g., book, film, etc.  Matched with
field heading MEDIA.
.PP
An unknown sequence won't bother \fBminlib\fR; it will just fill
up that field with spaces.
.RE
.SH FILES
\fBminlib\fR uses two files primarily:  the data, or library
file, which has the actual library information in it, and a
run-control, or config file, which contains simple lines to
control \fBminlib\fR's behavior.
.SS The Data File
The data file, or library file, is a pretty simple "cookie
jar" format, consisting of multi-line records separated by
lines containing two percentage marks, or (\fB%%\fR).  No
line can contain the text "\fB%%\fR" except record
separating lines; \fBminlib\fR will always consider such
lines to be starting a new record.
.PP
\fBPlease note that every record requires a %% to begin it,
including the first in a file.\fR
.PP
Between each record-separating line are the individual
fields of the record.  These consist of a field name in all
capital letters, a colon, and then the text of the field.
After the colon, whitespace can be inserted or deleted at
will, with no change in how \fBminlib\fR reads the line.
Each field must be contained entirely on one line, however.
.PP
An example record:
.RS
%%
.br
TITLE:  My Very Favorite Book
.br
AUTHLAST:  Publick
.br
AUTHMID: Q
.br
AUTHFIRST:  John
.br
GENRE:  Scifi
.br
LANGUAGE:  English
.br
YEAR:	1998
.br
MEDIA:  book
.RE
You then repeat this as many times as you need to to build
your library database.
.PP
Because \fBminlib\fR accepts multiple files at the same
time, you can divide your library files however you wish,
and \fBminlib\fR will accept whichever files you specify,
sort them all together, and display them to you.  So you can
have one file with your books, one with your movies, one
with your music, and one with your vintage 8-tracks of
original Swedish ABBA and still get them all at once if you
want.
.PP
There are no artificial limits on the fields you can
include; if you particular library database requires "FOO"
as a field, just put it in there.  \fBminlib\fR will not be
able to sort your records by fields it doesn't know;
however, it will be able to search for such fields, and it
will be able to display such fields in its detail view, when
you select a record.
.PP
For fields that \fBminlib\fR knows, see the section on the
\fB\-r\fR option above.
.SS Run-Control File
The run-control file ("rc" or "config" file) contains the
configurable options for \fBminlib\fR to use.  Note that
when options specified on the command line conflict with
those in the config file, the options on the command line
will take precedence.
.SH EXIT STATUS
\fBminlib\fR returns 0 if successful, non-zero if it fails
for some reason.  See the \fBERRORS\fR section for possible
failure exit statuses.
.SH ERRORS
\fBminlib\fR can, like all programs, go wrong in a huge
number of ways; but fortunately, most of those are extremely
unlikely.  Still, \fBminlib\fR tries hard to give precise
failure information, even for those situations that
basically never happen.
.PP
So upon failure, \fBminlib\fR prints both an error message
to \fIstderr\fR and exits with a particular status.  Error
codes are as follows:
.TP
.BR 1
You gave \fBminlib\fR an option that it doesn't recognize.
.TP
.BR 2
You supplied \fBminlib\fR an option which requires an
argument, but didn't send it an argument.  E.g., you said
\fB\-r\fR, but didn't say what you wanted the formatting
string to be.
.TP
.BR 3, 4, 5, 6, 7, 9
Insufficient memory errors; this are only thrown when the
operating system can't provide enough memory for
\fBminlib\fR to do its thing.  Since \fBminlib\fR doesn't
require much memory, these errors are exceedingly unlikely.
\fB3\fR means it couldn't load the data file; \fB4\fR means
means that it couldn't load the data file into formatted
lines; \fB5\fR means that it couldn't load the array used to
track the formatted lines; \fB6\fR means that it couldn't
get enough memory for the format string; \fB7\fR
indicates insufficient memory for a variety of minor
internal tasks; \fB9\fR means there is insufficient memory
for the filename string.
.TP
.BR 8
A problem opening the data file.
.SH BUGS
None known at this time.
.SH AUTHOR
Donald P. Goodman III <dgoodmaniii at gmail dot com>
.SH SEE ALSO
pdfinfo
