." +AMDG
." Process with:
." groff -man -Tascii minlib.1
.TH minlib 1 "May 2016" Linux "User Manuals"
.SH NAME
minlib \- a text-based library management program
.SH SYNOPSIS
.B minlib [OPTIONS]
.SH DESCRIPTION
.B minlib
A text-based library management program, designed to do one
thing---manage your library, physical and digital---and do
it well. Customizable formatting, usable with books, files,
movies, music; filtering, searching, and more, all focused
on that one task.
.SH OPTIONS
.IP -v
Print version and licensing information, then exit
successfully.
.IP "-f filename"
Use
.I filename

.SH SLOTS

.SH ROULETTE

.SH CRAPS


.SH BUGS
None known at this time.
.SH AUTHOR
Donald P. Goodman III <dgoodmaniii at gmail dot com>
